### ISSUE TITLE
block()/blockFirst()/blockLast() are blocking error when calling bodyToMono

### ISSUE THREAD

**Issue by wang-xiaowu** [kptfh/feign-reactive-sample#4]
when i try feign-server's interface "/greeting"
i get a error "block()/blockFirst()/blockLast() are blocking error when calling bodyToMono AFTER exchange()"
please take a look ,thank u

**Comment by ahunigel** [comment]
I've tried this after upgrade to 3.1.0, this issue DO exists

**Comment by kptfh** [comment]
fixed in version 3.2.0
